version: '3'
services: 
  postgres-container:
      image: postgres
      container_name: postgres-container
      networks:
        - production-network
      ports:
        - "5432:5432"
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      environment:
        - POSTGRES_PASSWORD=marcus@1234
networks:
  production-network:
      driver: bridge


